#!/usr/bin/env python3

import os
os.environ['FERNET_SECRET_KEY'] = 'JBK1jUlzIlND3JyFwrxp0M_XOZejD-ftrTPmM1lMGgY='
print(os.environ.get('FERNET_SECRET_KEY'))

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
import odoo

if __name__ == "__main__":
    odoo.cli.main()
